spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL57Dialect
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
      database: mysql
      defer-datasource-initailization: 'true'
      show-sql: 'true'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: 'true'
    password: loveloveshot
    username: loveloveshot
    url: jdbc:mysql://localhost:3306/loveloveshot?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&useUnicode=true&serverTimezone=Asia/Seoul
    profiles:
      active: dev